name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_links: ^4.0.1
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage:
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/images/
    - .env
