enum Category{
    Automotive,
    Beauty,
    BeautyCosemtics,
    BeautySoap,
    Books,
    BooksFiction,
    BooksNonFiction,
    Electronics,
    ElectronicsPhone,
    ElectronicsPc,
    FashionMen,
    FashionWomen,
    FashionBoys,
    FashionGirls,
    FashionShoes,
    FashionBoysShoes,
    FashionGirlsShoes,
    Home,
    HomeKitchen,
    HomeToilet,
    Movies ,
    Other,
    Software,
    SoftwareGames,
    Toys,

}
